# Generated by Django 5.0.2 on 2025-05-16 07:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('air_quality', models.FloatField()),
                ('co2_level', models.FloatField()),
                ('temperature', models.FloatField()),
                ('noise_level', models.FloatField()),
                ('humidity', models.FloatField()),
                ('particulate_matter', models.FloatField()),
                ('location', models.CharField(default='Factory Floor A', max_length=100)),
                ('sensor_id', models.CharField(default='ENV-SENSOR-001', max_length=50)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
